services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app-service-next
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
